AppBundle\Entity\Category:
    type: entity
    table: category
    id:
        categoryId:
            type: boolean
            nullable: false
            id: true
            column: category_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 25
            fixed: false
        lastUpdate:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: last_update
    manyToMany:
        film:
            targetEntity: Film
            cascade: {  }
            mappedBy: category
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
