AppBundle\Entity\Customer:
    type: entity
    table: customer
    indexes:
        idx_fk_store_id:
            columns:
                - store_id
        idx_fk_address_id:
            columns:
                - address_id
        idx_last_name:
            columns:
                - last_name
    id:
        customerId:
            type: smallint
            nullable: false
            unsigned: true
            id: true
            column: customer_id
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: last_name
        email:
            type: string
            nullable: true
            length: 50
            fixed: false
        active:
            type: boolean
            nullable: false
            default: '1'
        createDate:
            type: datetime
            nullable: false
            column: create_date
        lastUpdate:
            type: datetime
            nullable: true
            default: CURRENT_TIMESTAMP
            column: last_update
    manyToOne:
        address:
            targetEntity: Address
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                address_id:
                    referencedColumnName: address_id
            orphanRemoval: false
        store:
            targetEntity: Store
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                store_id:
                    referencedColumnName: store_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
